### ISSUE TITLE
Compatibility issue with trl==0.20.0: PPOTrainer missing generate method

### ISSUE THREAD

**Issue by kaikaikaidian** [Wuyxin/collabllm#12]
I'm trying to run the `ppo.py` script but encountered an issue with the trl (0.20.0). When executing the code, I get the following error:

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/miniconda3/envs/collabllm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/root/miniconda3/envs/collabllm/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/root/autodl-tmp/CollabLLM/scripts/train/ppo.py", line 521, in <module>
[rank0]:     main()
[rank0]:   File "/root/autodl-tmp/CollabLLM/scripts/train/ppo.py", line 476, in main
[rank0]:     response_tensors = trainer.generate(query_tensors, return_prompt=False, **generation_kwargs)
[rank0]: AttributeError: 'PPOTrainer' object has no attribute 'generate'
```
Questions​​:

1. Which version of trl was the code developed/tested with?
2. Does the project use a custom implementation of PPOTrainer?
Any guidance on resolving this compatibility issue would be greatly appreciated. Thank you!

**Comment by Wuyxin** [comment]
Hi, 

Could you send me the public link of the ppo.py script? 

The PPOTrainer in trl 0.20 is not supported because the trl team moves the reward computation inside of the PPOTrainer. Therefore I did not include the ppo.py in the main branch. But as far as I know, the trl team is working on integrating CollabLLM as one of their trainers.

I used to use trl 0.10.1 for PPOTrainer, but I will need to verify whether this still works if you can let me know which script you are using. Thanks!

**Comment by Wuyxin** [comment]
I have updated the ppo.py script, the previous ppo script is outdated.

https://github.com/Wuyxin/collabllm/blob/main/scripts/train/ppo.py - This one should work with trl=0.10.1 and vllm>0.9.0

You might want to use a smaller model to test first (since the vllm takes some memory on each GPUs) and set a larger batch size. Let me know if any issues comes up!

**Comment by kaikaikaidian** [comment]
Thank you! Following your guidance on trl==0.10.1 and vllm>0.9.0 using the updated script, the PPO training successfully completed. I appreciate you taking the time to resolve this.

**Comment by Wuyxin** [comment]
No problem :)
